# Constantes partagees pour le jeu
WALL_HEIGHT = 50
PLATFORM_BOTTOM_OFFSET = 165
OBSTACLE_DEFAULT_SIZE = (50, 50)
OBSTACLE_SPAWN_MIN_MS = 1200
OBSTACLE_SPAWN_MAX_MS = 3000
DEFAULT_OBSTACLE_SPEED = 5.0

# G-Switch style tuning..
GAME_SPEED_START = 5.0
GAME_SPEED_MAX = 12.0
GAME_ACCEL_PER_FRAME = 0.0018
PLAYER_GRAVITY_SPEED = 7
SPAWN_MIN_FLOOR_MS = 550
SPAWN_MAX_FLOOR_MS = 1200
